version: '3.9'

services:

  postgres-fastapi:
    image: postgres:14.5
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    depends_on:
      - postgres-fastapi
    volumes:
      - cache_data:/data

  file-server:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    command: sh -c "${COMMANDS_FS}"
    volumes:
      - media_data:/app/media/
    depends_on:
      postgres-fastapi:
        condition: service_healthy

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart:
      always
    depends_on:
      - file-server

volumes:
  postgres_data:
  cache_data:
  media_data:
